import { type MigrationInterface, type QueryRunner } from 'typeorm';

/**
 * Creates the complete inventory schema from scratch.
 *
 * The migration is written as explicit SQL rather than generated, so every
 * constraint and index is reviewable and the database enforces the domain rules
 * independently of the application layer. `down()` is exhaustive, which is what
 * makes "rebuild the database from zero" an actually testable claim.
 */
export class InitSchema1755300000000 implements MigrationInterface {
  name = 'InitSchema1755300000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Trigram index support, used by the advanced search (QUERY /items/search)
    // so that `ILIKE '%term%'` can be served from an index instead of a
    // sequential scan over the whole items table.
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS pg_trgm`);

    // Shared trigger function keeping `updated_at` truthful even for writes
    // that bypass the ORM (manual SQL, future batch jobs).
    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION set_updated_at()
      RETURNS TRIGGER AS $$
      BEGIN
        NEW.updated_at = now();
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql
    `);

    // ---------------------------------------------------------------- groups
    await queryRunner.query(`
      CREATE TABLE "groups" (
        "id"          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name"        varchar(80)  NOT NULL,
        "description" varchar(255),
        "created_at"  timestamptz  NOT NULL DEFAULT now(),
        "updated_at"  timestamptz  NOT NULL DEFAULT now(),
        CONSTRAINT "chk_groups_name_length"
          CHECK (char_length(btrim("name")) BETWEEN 2 AND 80)
      )
    `);

    // Case-insensitive uniqueness: "Electronics" and "electronics" are the same
    // group. A plain UNIQUE constraint would let both exist.
    await queryRunner.query(`
      CREATE UNIQUE INDEX "ux_groups_name_lower" ON "groups" (lower("name"))
    `);
    await queryRunner.query(`CREATE INDEX "idx_groups_name" ON "groups" ("name")`);
    await queryRunner.query(`
      CREATE TRIGGER "trg_groups_updated_at"
        BEFORE UPDATE ON "groups"
        FOR EACH ROW EXECUTE FUNCTION set_updated_at()
    `);

    // ----------------------------------------------------------------- items
    await queryRunner.query(`
      CREATE TABLE "items" (
        "id"            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "group_id"      int           NOT NULL,
        "name"          varchar(120)  NOT NULL,
        "description"   varchar(500),
        "sku"           varchar(40)   NOT NULL,
        "quantity"      int           NOT NULL DEFAULT 0,
        "minimum_stock" int           NOT NULL DEFAULT 0,
        "unit_price"    numeric(12,2) NOT NULL DEFAULT 0,
        "created_at"    timestamptz   NOT NULL DEFAULT now(),
        "updated_at"    timestamptz   NOT NULL DEFAULT now(),
        CONSTRAINT "fk_items_group"
          FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE RESTRICT,
        CONSTRAINT "chk_items_name_length"     CHECK (char_length(btrim("name")) BETWEEN 2 AND 120),
        CONSTRAINT "chk_items_sku_length"      CHECK (char_length(btrim("sku")) BETWEEN 2 AND 40),
        -- Last line of defence for the core inventory invariant. Even a bug in
        -- the service layer or a manual UPDATE cannot drive stock negative.
        CONSTRAINT "chk_items_quantity"        CHECK ("quantity" >= 0),
        CONSTRAINT "chk_items_minimum_stock"   CHECK ("minimum_stock" >= 0),
        CONSTRAINT "chk_items_unit_price"      CHECK ("unit_price" >= 0)
      )
    `);

    await queryRunner.query(`CREATE UNIQUE INDEX "ux_items_sku" ON "items" ("sku")`);
    await queryRunner.query(`CREATE INDEX "idx_items_group_id" ON "items" ("group_id")`);
    // Serves the free-text search of QUERY /items/search.
    await queryRunner.query(`
      CREATE INDEX "idx_items_name_trgm" ON "items" USING gin ("name" gin_trgm_ops)
    `);
    await queryRunner.query(`
      CREATE INDEX "idx_items_sku_trgm" ON "items" USING gin ("sku" gin_trgm_ops)
    `);
    // Partial index: low-stock rows are a small subset, so this stays tiny and
    // makes GET /items/low-stock cheap regardless of catalogue size.
    await queryRunner.query(`
      CREATE INDEX "idx_items_low_stock" ON "items" ("group_id")
        WHERE "quantity" <= "minimum_stock"
    `);
    await queryRunner.query(`
      CREATE TRIGGER "trg_items_updated_at"
        BEFORE UPDATE ON "items"
        FOR EACH ROW EXECUTE FUNCTION set_updated_at()
    `);

    // ------------------------------------------------------------- movements
    await queryRunner.query(`CREATE TYPE "movement_type" AS ENUM ('IN', 'OUT')`);

    await queryRunner.query(`
      CREATE TABLE "movements" (
        "id"              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "item_id"         int           NOT NULL,
        "type"            "movement_type" NOT NULL,
        "quantity"        int           NOT NULL,
        "reason"          varchar(255),
        "resulting_stock" int           NOT NULL,
        "created_at"      timestamptz   NOT NULL DEFAULT now(),
        CONSTRAINT "fk_movements_item"
          FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON DELETE CASCADE,
        CONSTRAINT "chk_movements_quantity"        CHECK ("quantity" > 0),
        CONSTRAINT "chk_movements_resulting_stock" CHECK ("resulting_stock" >= 0)
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "idx_movements_item_id_created_at"
        ON "movements" ("item_id", "created_at" DESC)
    `);
    await queryRunner.query(`CREATE INDEX "idx_movements_type" ON "movements" ("type")`);
    await queryRunner.query(`
      CREATE INDEX "idx_movements_created_at" ON "movements" ("created_at" DESC)
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "movements"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "movement_type"`);

    await queryRunner.query(`DROP TRIGGER IF EXISTS "trg_items_updated_at" ON "items"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "items"`);

    await queryRunner.query(`DROP TRIGGER IF EXISTS "trg_groups_updated_at" ON "groups"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "groups"`);

    await queryRunner.query(`DROP FUNCTION IF EXISTS set_updated_at()`);
    // pg_trgm is intentionally left installed: it is a database-wide extension
    // that other schemas may rely on, and dropping it is not this migration's
    // business.
  }
}
